### ISSUE TITLE
FOV Modification

### ISSUE THREAD

**Issue by Protomanez** [Lyall/GBFRelinkFix#1]
Awesome Mod! Would it be possible to allow the user to modify the FOV to a custom value as well please?

**Comment by Lyall** [comment]
It should be possible yeah. I already have an FOV hook for gameplay/cutscenes to fix issues with <16:9 aspect ratios. It might end up being a multiplier instead of a specific degree control though.

**Comment by Protomanez** [comment]
Thank you for the prompt response! Hopefully this can be incorporated soon, I will look forward to any updates.

Thanks for all your work once again, you rock

**Comment by Lyall** [comment]
I've added gameplay FOV modification in the latest release (v1.0.1). Let me know what you think!

**Comment by Protomanez** [comment]
Just what I was looking for! Closing this 👍
