### ISSUE TITLE
[feature request] Separate the "HUD span" for field view

### ISSUE THREAD

**Issue by yelnis** [Lyall/GBFRelinkFix#14]
Hi there,

Thank you very much for your great support!! I can play GBF-Relink with my ultra wide monitor. It's awesome!!

I'd like to put HUD outside in field view for battle and town, but other HUD layout will be broken such as quest counter, and party menu. 
Would you separate [HUD span] option for field view?
It is very nice for me, put quest and party menus keep 16:9 position. On the other hand, field view HUD of party member status, abilities pane, and potions pane are putting outside of screen.

It looks your source searching memory patterns and modify near parameters. I guess specified HUD components may be able to put different positions. Do you think it is available or not this option?

At first, I have tried clone and open with Visual Studio pro 2022. Unfortunatly, my VS2022 can't resolve external libraries paths. If available, please describe your development environment and configuration in README.

Best regards.

**Comment by Lyall** [comment]
Added this as of [v1.0.2](https://github.com/Lyall/GBFRelinkFix/releases).

**Comment by yelnis** [comment]
Hi @Lyall,
Thank you for your support imeediately! It's my expectation.
