### ISSUE TITLE
[feature request] Proper fullscreen mode compatible with AMD Fluid Motion Frames possible?

### ISSUE THREAD

**Issue by Dolyfin** [Lyall/GBFRelinkFix#15]
I believe this is just an annoying issue with the game as it uses some weird fullscreen mode that just doesn't work with AFMF. I have yet to figure out any workaround for the drivers to work with the game. 

![image](https://github.com/Lyall/GBFRelinkFix/assets/55581931/0f7a907c-ae12-4802-be33-43647720217c)

If you could help figure out or shine more info on the fullscreen modes that would be great!

**Comment by DAOWAce** [comment]
Have you tried SpecialK? https://www.pcgamingwiki.com/wiki/Special_K

**Comment by Dolyfin** [comment]
> Have you tried SpecialK? https://www.pcgamingwiki.com/wiki/Special_K

Thank you. Although Special K didn’t directly fix the issue. I had the tested with help from the discord that the overlay from MedalTV prevented Hardware Composite Flip. The game didn’t need to be in exclusive full screen or anything. Disabling the overlay was all that is needed.
