### ISSUE TITLE
Span background does not work well with 16:10

### ISSUE THREAD

**Issue by mbushnaq00** [Lyall/GBFRelinkFix#16]
When I enable span background on a 16:10 display (in my case its the legion go), I get black borders on all corners and the image does not look right at all. I have to keep using the default 16:9 background for now , but that leaves the top and the bottom be visible during loading screens and menu view

**Comment by Lyall** [comment]
That's [v1.0.2](https://github.com/Lyall/GBFRelinkFix/releases) out, it should hopefully address your issue.

**Comment by mbushnaq00** [comment]
Thanks a lot for your support, it seems the issue is now resolved with the latest version

**Comment by mbushnaq00** [comment]
Thanks a lot for your support, it seems the issue is now resolved with the latest version
