### ISSUE TITLE
[Bug]:  Won't work for me

### ISSUE THREAD

**Issue by CoolName96** [Lyall/GBFRelinkFix#17]
## Issue Summary:
I put the contents of the folder into my game directory, and it still loads like a 16:9. I'm using a 21:9 monitor and everything I've tried doesn't work.

**Comment by Lyall** [comment]
Can you show a screenshot of the contents of your game folder? Also does it generate a `GBFRelinkFix.log` file?

**Comment by Delvecci** [comment]
Can you help too I try the same thing, I have the GBFRelinkFix.log file but whatever I do it doesn't adjust it

**Comment by Delvecci** [comment]
![Screenshot 2024-02-09 232622](https://github.com/Lyall/GBFRelinkFix/assets/143835094/4218e5a3-9f2f-44ba-a600-779b6a435b15)
![Screenshot 2024-02-09 232650](https://github.com/Lyall/GBFRelinkFix/assets/143835094/d222056b-0eb3-4845-8264-4c888923a034)
![Screenshot 2024-02-09 232728](https://github.com/Lyall/GBFRelinkFix/assets/143835094/2a90b68c-ba5a-411e-9a86-46ff9346be4e)
