### ISSUE TITLE
False Positive www.virustotal.com ?

### ISSUE THREAD

**Issue by emerylopes** [Lyall/GBFRelinkFix#20]
https://www.virustotal.com/gui/file/78cfe4c841c0b42906c5ff85a1d021142f661a162be574db6c891066150a9a9b/detection

CrowdStrike Falcon
Win/malicious_confidence_60% (D)
Cynet
Malicious (score: 100)
MaxSecure
Trojan.Malware.300983.susgen

**Comment by Lyall** [comment]
It's a false positive as you say. The source code is wide open to be perused by anyone. The release builds are also compiled by GitHub actions.
