### ISSUE TITLE
[Feature Request]:  Proper HUD placement for 21:9

### ISSUE THREAD

**Issue by jakeblake1122** [Lyall/GBFRelinkFix#21]
## Feature Summary:
Is there any plans for proper HUD placement on 21:9?

It would be nice to have the HUD in the corners of the screen rather than in the middle where it is now.

**Comment by Lyall** [comment]
It's already a feature. It's just disabled by default in the ini.

![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/2fe43fac-0388-445b-b57b-dbe6f3e37a4f)
