### ISSUE TITLE
[Feature Request]: Fine Adjustment of HUD Span on Ultra / Super Ultrawide resolutions?

### ISSUE THREAD

**Issue by TurboBeef** [Lyall/GBFRelinkFix#22]
Wondering if there is a means to set a distance smaller than the total width when spanning the game HUD?

On a 32:9 resolution (5120 x 1440 for example) some super ultrawide fixes in other applications I have seen will have the option to span the hud out partially instead of completely to the resolution border.

For example, gameplay rendering uses the full resolution of 5120 x 1440 but the hud is constrained to an equivalent 21:9 width (3440 x 1440 in this case). A hard set value, or a % adjustment would be a welcome feature if possible. 

So far this project has been everything one should hope for in achieving compatibility with these resolutions, thank you for your excellent work.

**Comment by Lyall** [comment]
That would be doable for sure.  How would you like it implemented? Something like this?

![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/e7d9e5f9-5b9a-4734-9bb6-cfb75955e467)

**Comment by TurboBeef** [comment]
That seems like the most logical way to implement it to me, I think that would be great. 

Based on how the current span (and all the ultrawide settings actually) feature works, when enabled but still playing in 16:9 there is no effect, which is good! This means in Big Picture mode on Steam no config changes are needed when switching from Ultrawide a 16:9 display. Will (or could) this functionality remain the same if this feature is added?

**Comment by DAOWAce** [comment]
Side note: Can spanned HUD be the default (21:9 fit)?  Is there a reason why it isn't?

I didn't change it for a number of days as I thought it meant "stretch", but just tried and it, it moved the UI to the edges like I've wanted this whole time. Maybe that's my fault for not understanding the word, but I'm sure 99% of 21:9 users would want the HUD spanned by default.

**Comment by Lyall** [comment]
Apologies for the delay on this. I settled on this as a configuration method.

![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/672eb3e0-ce58-4b4e-a964-16721314aa6e)

I think that should work for most people and makes a bit more sense than a percentage. Should be out to test on v1.0.4


> Side note: Can spanned HUD be the default (21:9 fit)? Is there a reason why it isn't?
> 
> I didn't change it for a number of days as I thought it meant "stretch", but just tried and it, it moved the UI to the edges like I've wanted this whole time. Maybe that's my fault for not understanding the word, but I'm sure 99% of 21:9 users would want the HUD spanned by default.

There's no reason really, it was mainly disabled at first because it didn't work very well and I didn't think people would want to use it. Now that it's fixed up and properly spans all the HUD I don't see why it shouldn't be enabled by default.
