### ISSUE TITLE
[Bug]: Issue with dialog anime when fix is enabled

### ISSUE THREAD

**Issue by mbushnaq00** [Lyall/GBFRelinkFix#24]
## Issue Summary: During a dialog a weird faded background is shown instead of the anime (screenshot attached)
![game1707671182173](https://github.com/Lyall/GBFRelinkFix/assets/63579710/774b19fe-40c3-423c-a738-9af30e278176)

**Comment by Lyall** [comment]
Can you post your `GBFRelink.log` file please?

**Comment by Lyall** [comment]
Actually, don't need the log. I spotted the issue and it should be resolved in v1.0.4
