### ISSUE TITLE
Maybe a user issue

### ISSUE THREAD

**Issue by PinTaiL707** [Lyall/GBFRelinkFix#26]
Im sure that this is just a user issue but I downloaded the zip and extracted all files to local game file location, changed the .ini file and im not seeing any changes.  I put 3840 x 1600 but im not seeing that option in the display settings or when i load into the world.  What am i doing wrong?  Screenshots for reference. 
![GBF screenshot](https://github.com/Lyall/GBFRelinkFix/assets/159838785/07cf7d05-b8f9-473e-aca2-1ee34e20974b)
![gbr screenshot 2](https://github.com/Lyall/GBFRelinkFix/assets/159838785/bf82a6c7-b7ca-41a1-96bf-af86a589e64b)

**Comment by Lyall** [comment]
You've downloaded the source code by mistake, you want to download the release build.

![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/62752728-ac8a-475f-bf27-881da32cf9ea)
![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/5d529959-7edf-42ba-a70b-06a180528db3)

**Comment by PinTaiL707** [comment]
You are a lifesaver! thank you so much for this and the quick response! will definitely donate!
