### ISSUE TITLE
[Bug]: Game not running when used with Reloaded ll and Special K

### ISSUE THREAD

**Issue by DeaWonChoi** [Lyall/GBFRelinkFix#29]
## Issue Summary:
Game not running when used with Reloaded ll and Special K

## GBFRelinkFix & Game Version Numbers:
GBFRelinkFix: 1.0.4
Game Version: 1.0.5

## Log Files:
[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14314169/GBFRelinkFix.log)

## Reproduction:
I installed 3 of them to use ultrawide with various mods.
    -Reloaded-ll
    - Special K
    -GBFRelinkFix
And the game was never played again.

To find the cause of this problem, I repeated several installations and deletions and was able to figure out which file was causing the problem.

Originally, Reloaded-ll could not be used with Special K, but a way to use both at the same time in Nexus mode was recently revealed.
(https://www.nexusmods.com/granbluefantasyrelink/mods/29)

So I installed a mod to remove fog, DOF, motion blur, bloom from Reloaded-ll and used the DualSense 4 icon mod from Steam using Special K.

(https://www.nexusmods.com/granbluefantasyrelink/mods/17)
(https://www.nexusmods.com/granbluefantasyrelink/mods/5?tab=description)
*DualSense cannot be used with Xbox button images. It's very difficult.

And finally, I installed this mod to apply ultrawide, but the game did not run.

In the above process, I worked to connect the two programs.
At this time, a file called **WINMM.dll** is created in the game installation path.

It's not clear what this file does, but as long as this file and GBFRelinkFix coexist, the game will not run.

Let me write down some of the test results.
Reloaded-II + GBFRelinkFix = No problem
Reloaded-II + Special K linkage = no problem
GBFRelinkFix + Special K = No problem

Installing GBFRelinkFix with Reloaded-II + Special K connected = Problem!!

P.s. This wouldn't have happened if I had only installed the mod that changed the Xbox pad button icon to Dual Sense via Reloaded-II.

I used Google Translate for translation. sorry

**Comment by ibaraRinne** [comment]
How to let Reloaded-II and GBFRelinkFix work together?
If remove the file called WINMM.dl ,MOD  can work but ultrawide not

**Comment by SupDos** [comment]
@DeaWonChoi @ibaraRinne, you can follow the steps in this PR https://github.com/Lyall/P3RFix/pull/21. Works on both Windows and Steam Deck for me on Relink as well.

If Lyall is happy with the instructions I’ll PR them here too

**Comment by DeaWonChoi** [comment]
@SupDos 
![image](https://github.com/Lyall/GBFRelinkFix/assets/35949891/d5b3a9d8-2364-499e-8b73-74ad341ad1a8)
![image](https://github.com/Lyall/GBFRelinkFix/assets/35949891/d7f0760b-9951-4268-8304-15583b3608bb)

Using the instructions as a guide, I did the following:

The result is: the game does not run

Am I understanding this correctly?

![image](https://github.com/Lyall/GBFRelinkFix/assets/35949891/b7301a27-ec79-47b0-82dd-502b12b31c0e)


Although the ps5 icon application mode that was my goal has now been released as reloaded2 mode and does not affect my gameplay, this problem should still be treated as an issue if it can be resolved.

**Comment by DeaWonChoi** [comment]
> How to let Reloaded-II and GBFRelinkFix work together? If remove the file called WINMM.dl ,MOD can work but ultrawide not

I used Reloaded2 + GBFRelinkFix and had no problems from the start.

If the game does not run even after deleting WINMM.dll, it is recommended to check its integrity or cleanly delete the game and then reinstall it.

**Comment by Lyall** [comment]
Both `dinput8.dll` and `winmm.dll` are ASI loaders. You should only have one of them, if you are using Reloaded II then you can safely delete `dinput8.dll` and let it's ASI loader load GBFRelinkFix from the scripts folder.

**Comment by DeaWonChoi** [comment]
> Both `dinput8.dll` and `winmm.dll` are ASI loaders. You should only have one of them, if you are using Reloaded II then you can safely delete `dinput8.dll` and let it's ASI loader load GBFRelinkFix from the scripts folder.

okay. I understood it right away.
I deleted dinput8.dll and only left winmm.dll.
This game runs without issue and all modes work.

Also, I think I need some guidance on understanding @SupDos 
Since dinput8.dll is distributed here, anyone who uses both Reloaded 2 and Special K must delete dinput8.dll.

thank you

**Comment by SupDos** [comment]
> Since dinput8.dll is distributed here, anyone who uses both Reloaded 2 and Special K must delete dinput8.dll.

Yeah, the instructions I wrote are assuming you're starting from scratch, but maybe I should add a note saying to delete the .dll file that GBFRelinkFix/other Lyall fixes provide before starting, in case someone left it there accidentally...

**Comment by ElisaKyu** [comment]
Hello, can anyone here please help.
I using Reloaded II + GBFRelinkFix
I can run the game, but my game screen enter first person mode 
and i need to restart game 4 - 5 times or more to get it back to normal. 
is there a fix for this?

**Comment by Lyall** [comment]
I have released [v1.0.5](https://github.com/Lyall/GBFRelinkFix/releases/tag/v1.0.5) to hopefully aid in compatibility with Reloaded-II.

**Comment by DeaWonChoi** [comment]
> I have released [v1.0.5](https://github.com/Lyall/GBFRelinkFix/releases/tag/v1.0.5) to hopefully aid in compatibility with Reloaded-II.

If there are no more issues, we will consider it resolved and close this issue.
