### ISSUE TITLE
Curious to know what the memory patterns are?

### ISSUE THREAD

**Issue by emrahsungu** [Lyall/GBFRelinkFix#3]
There are couple of memory patterns that you search for, example
```
uint8_t* FPSCapScanResult = Memory::PatternScan(baseModule, "4C ?? ?? FF ?? 48 ?? ?? ?? 48 ?? ?? ?? ?? ?? ?? 48 ?? ?? 48 ?? ?? ?? ?? ?? ?? C4 ?? ?? ?? ??");
```
How did you come accross these? what do they mean?
Could you please give a little explanation?

**Comment by Lyall** [comment]
They're patterns of code. Basically I find the part of code I want to edit, then create a pattern to scan for. The potentially variable parts are wildcarded with question marks, like offsets or addresses. This means that if the game gets a patch and memory addresses change a little or offsets change then the pattern still works.

**Comment by emrahsungu** [comment]
thank you very much for the explanation. I am sorry I couldnt explain myself clearly. Without having a pdb symbol file how did you come accross the code pattern that you now changes the resolution etc 🙇 
Thank you for taking your time

**Comment by Lyall** [comment]
That's the harder part. It's just time spent reverse engineering how parts of the game work by using a disassembler. Something like x64dbg, IDA or Cheat Engine do the job.

**Comment by emrahsungu** [comment]
I see thanks a lot! I am very well versed with Ghidra and have some experience with windbg but I would have a very hard time to deal with an executable that big without symbol file. Could you please give me some hints about the tools you actually used, and how you used? If you could get me started, I can take off from there. I appreciate your time 🙇

**Comment by Lyall** [comment]
I'd start with something like cheat engine. It's very easy to use and has a powerful scripting system using LUA. I usually prototype my work in Cheat Engine then write it out in C++. Beyond that I'd suggest looking online, there's bound to be loads of tutorials about this type of thing.

**Comment by emrahsungu** [comment]
Thanks a lot! So in this case I also assume, you started with Cheat Egnine, extracted memory patterns, then automate it with cpp 🙇

**Comment by Lyall** [comment]
That's kind of it yeah. The hard part is figuring it all out really. Like in this game there's graphical corruption at certain resolutions but not at others. Tracking that down to a specific function expecting a rounded number is tricky.
