### ISSUE TITLE
[Bug]: Odd autodetected HUD layout with Span HUD Aspect Ratio = 0

### ISSUE THREAD

**Issue by poteto** [Lyall/GBFRelinkFix#30]
## Issue Summary:

I just updated to GBFRelinkFix 1.0.5 from 1.0.3 and noticed the HUD looks off. Peeking at the logs and wildly guessing, it seems like the aspect ratio might not be auto detecting correctly?

Confirmed by manually setting my Span HUD AspectRatio to 2.3888, which fixes it.

## GBFRelinkFix & Game Version Numbers:

GBFRelinkFix 1.0.5
Game version 1.0.5

![image](https://github.com/Lyall/GBFRelinkFix/assets/1390709/cab99db6-8d16-4978-9864-ae9347ab918b)

## Log Files:

[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14354371/GBFRelinkFix.log)

## Reproduction:

![image](https://github.com/Lyall/GBFRelinkFix/assets/1390709/863044e8-834e-486d-836d-dc00453523c2)

Download and unzip 1.0.5, start game with default GBFRelinkFix settings.

**Comment by Lyall** [comment]
Thanks for the detailed report! And you're spot on with identifying the issue!

Looks like I made a silly copy+paste error. When `fHUDAspectRatio` is set to 0, it's supposed to automatically set it to your aspect ratio but I'd accidently deleted that part of code in the commit (whoops). I have fixed this error and released [v1.0.6](https://github.com/Lyall/GBFRelinkFix/releases/) with it included.

**Comment by poteto** [comment]
Awesome, glad it was useful! And thanks so much for creating this mod 🤍
