### ISSUE TITLE
[Bug]: Depart animation bug

### ISSUE THREAD

**Issue by Pinduca23** [Lyall/GBFRelinkFix#31]
## Issue Summary:

The game gets stuck in the animation after choosing to depart in the Grandcypher to another island, it stays that way for about 2 min then gets to the next scene. This happened 2 times already (chapter 3 and 4), my only "fix" was removing the Ultrawide mod so I could see what was happening and after the loading screen I reload the mod in my game files.

## GBFRelinkFix & Game Version Numbers:

Game version 1.0.4
GBFRelinkFIx version 1.0.4

## Log Files:

[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14361119/GBFRelinkFix.log)

Specs:
Ryzen 5 7600X
32GB 5200 Mhz
Radeon RX 6750 XT

## Reproduction:

Depart to a new island aboard the Grandcypher or Rolan's ship
![bug](https://github.com/Lyall/GBFRelinkFix/assets/78888827/1bf42e34-e3d6-4fdf-af5a-bbe38e0f868b)

**Comment by Lyall** [comment]
This sounds the same as issue #12. The fix for that user ended up being to reinstall the game. Can you give that a try or possibly verify game files through Steam?

**Comment by Pinduca23** [comment]
Did just that and it somehow went away.
Thanks for the fix!
