### ISSUE TITLE
[Bug]: 1,06 -> GBFRelinkFix.ini not found (easily?)

### ISSUE THREAD

**Issue by tomvoelske** [Lyall/GBFRelinkFix#32]
## Issue Summary:

When the game loads, it is unable to find the .ini file. I've had it work once and once only, and not been able to replicate it since.

## GBFRelinkFix & Game Version Numbers:

GBFRelinkFix 1,06 | Game version whatever it is as of 25/02/2024

## Log Files:

[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14395141/GBFRelinkFix.log)

## Reproduction:

![image](https://github.com/Lyall/GBFRelinkFix/assets/53340385/8e869c6f-3d3f-4998-8e02-7aa30ec2fae0)

![image](https://github.com/Lyall/GBFRelinkFix/assets/53340385/540e3e96-4eb2-4bc4-96f2-63583f0d7e8d)

The folder "./scripts/scripts" is created upon log generation

![image](https://github.com/Lyall/GBFRelinkFix/assets/53340385/1811a839-ab6e-4636-965a-b9d777586660)

My system volume for GBR is J: in case some default of C: is being used in the code

Please note that all files are exactly as from the 1.06 download - I haven't made any changes

**Comment by Lyall** [comment]
That second scripts folder is just a bug with log generation that'll be fixed in the next version. It shouldn't affect functionality of the fix though. Can you post the log file from the `scripts/scripts` folder in your last screenshot? If it can't find the config file, it will say as much in the log file.

**Comment by tomvoelske** [comment]
Hey, I did post it above but I know it kind of blends with the rest of the text. I'll post it again here:

[GBFRelinkFix(1).log](https://github.com/Lyall/GBFRelinkFix/files/14407425/GBFRelinkFix.1.log)

I didn't try putting the missing files into the new /scripts folder to test, but I do remember it working once and then not after, so perhaps the base path was messed up when the new /scripts folder was made? Not sure.

**Comment by Lyall** [comment]
> Hey, I did post it above but I know it kind of blends with the rest of the text. I'll post it again here:

My mistake, time to get my eyes checked!

> I didn't try putting the missing files into the new /scripts folder to test, but I do remember it working once and then not after, so perhaps the base path was messed up when the new /scripts folder was made? Not sure.

Can you try this [test build](https://github.com/Lyall/GBFRelinkFix/files/14410401/GBFRelinkFix_v1_0_7_test.zip)? I've set log generation to use an absolute path which should fix that erroneous scripts folder appearing. Also added more logging for file paths so you can see where the fix thinks your log file and config file are.

**Comment by tomvoelske** [comment]
Cheers, seems to work beautifully! The logs indicate no problems, but I'll upload them nonetheless just to aid in future releases etc.

[GBFRelinkFix - First run all default.log](https://github.com/Lyall/GBFRelinkFix/files/14413050/GBFRelinkFix.-.First.run.all.default.log)

[GBFRelinkFix - Second run all default.log](https://github.com/Lyall/GBFRelinkFix/files/14413051/GBFRelinkFix.-.Second.run.all.default.log)

[GBFRelinkFix - Third run with changes.log](https://github.com/Lyall/GBFRelinkFix/files/14413052/GBFRelinkFix.-.Third.run.with.changes.log)

And I didn't try beyond that, since I'm sure it's working happily now. Appreciate the work and amazing mod!
