### ISSUE TITLE
[Bug]: always have to reinstall the mod 

### ISSUE THREAD

**Issue by GospelVhae** [Lyall/GBFRelinkFix#33]
## Issue Summary:

Since yesterday's steam update, I have to reinstall the mod when I want to use it, otherwise, it bugs out. Screenshot attached
## GBFRelinkFix & Game Version Numbers:

Game version 1.0.5
Relink Fix v1.0.6

## Log Files:

Log files attached
i5 13500
Asus tuf 4070 12gb

## Reproduction:

booting up the game for the first time in the day results in the bugged fov/zoom
removing the mod restores the default settings
reinstalling the mod fixes the issue.

I have done this yesterday after steam's update. I had to do it again the next day

![image](https://github.com/Lyall/GBFRelinkFix/assets/159755095/f0588046-33c9-4a77-b39e-327a1502037b)
Already, you can see that the mod isn't working since it should be 21:9 on the load save screen

![image](https://github.com/Lyall/GBFRelinkFix/assets/159755095/aed8d7a1-989a-4c3e-8526-a1c800cc78ee)

![image](https://github.com/Lyall/GBFRelinkFix/assets/159755095/b22167b6-2b96-4d1c-be55-5f60be650e47)

[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14413991/GBFRelinkFix.log)

**Comment by GospelVhae** [comment]
Update. Tried reinstalling today and it doesn't work anymore. Attached new logs

[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14414045/GBFRelinkFix.log)

**Comment by Lyall** [comment]
Dupe of #32. The config isn't being detected properly. Should be fixed in release [v1.0.7](https://github.com/Lyall/GBFRelinkFix/releases).

**Comment by GospelVhae** [comment]
Yes, this released fixed it. Thanks!
