### ISSUE TITLE
Mod doesn't seem to be activating for v1.0.7?

### ISSUE THREAD

**Issue by DriftPrimed** [Lyall/GBFRelinkFix#36]
## Issue Summary:

I just installed Granblue today and installed your mod (thanks for helping out the ultrawide users!). The mod doesn't seem to be activating however. I installed it into the game folder under steam. I also tried to input custom resolution (3840x1600) but I cannot get it to activate (I am in the beginning on the ship). Please see screenshots below!

## GBFRelinkFix & Game Version Numbers:

Version v1.0.7 of GBFRelink. Game version is 1.0.5 (downloaded 03/02/2024)

## Log Files:

Since its not being activated, I don't see any log files being generated. Let me know if I am missing it.

## Reproduction:

Fresh install of the game. Tried multiple resolutions and fullscreen+borderless, no luck. ini file says "Enabled = true". 

![image](https://github.com/Lyall/GBFRelinkFix/assets/161963065/1174e98b-632a-4979-99ad-bfcc85fd45d5)
![image](https://github.com/Lyall/GBFRelinkFix/assets/161963065/e1336d7a-fcac-451e-8edd-40454a692af1)
![image](https://github.com/Lyall/GBFRelinkFix/assets/161963065/ca437c0d-49b8-4fb7-a16a-7bf088a6f835)

**Comment by Lyall** [comment]
You've downloaded the source code, not the release. You want to head to the releases section then download the zip from the assets section.

![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/916c2b51-69c6-4791-a725-0298db8c6d12)
![image](https://github.com/Lyall/GBFRelinkFix/assets/695941/38f9e30d-2e65-4314-aa69-37f1bb48c003)

**Comment by DriftPrimed** [comment]
Wow thank you, I'm new to github so didn't know about the release tab. It works perfectly now, thanks!
