### ISSUE TITLE
[Feature Request]: Inject AA?

### ISSUE THREAD

**Issue by HerbertHermann** [Lyall/GBFRelinkFix#38]
## Feature Summary:
Make injecting of AA through the grafic driver possible.

### Is your proposal related to a problem?
At the moment it´s not possible to inject AA through the nvidia contol pannel. You can disable the forced TAA with GBFRelinkFix but anyway no injection through nv control pannel.

### Describe the solution you'd like
If possible enable it with GBFRelinkFix.

**Comment by Lyall** [comment]
It's not really possible, as far as I can tell the game only has TAA and it's a DX11 title using deferred rendering so MSAA is off the table. You could try injecting SMAA/FXAA or something with Reshade for example, or even FXAA in the Nvidia control panel. Apart from that, as you've already mentioned, downsampling with DSR/VSR is a brute-force way of getting good image quality. 

For me personally I use DSR with the built-in TAA as that combination produces pretty good image quality to my eyes.
