### ISSUE TITLE
[Bug]: Taking damage causes a 16:9 black box to appear on 21:9

### ISSUE THREAD

**Issue by Sequincer** [Lyall/GBFRelinkFix#43]
## Issue Summary:
Since update 1.0.8, taking damage or being downed causes a black 16:9 square to appear anytime I take damage in any fight (the fights tested were Pyet-A and the Blackwyrm Dragon on Proud difficulty), reverting to 1.0.7 fixed this for me, but with the new update, that isn't a solution anymore. I am playing on a 3440x1440 resolution with a 21:9 aspect ratio. I think a bug post about this was made a few days back with screenshots but then was closed for some reason.

**Comment by Nyantaclaws** [comment]
I also am having this issue. Doesn't seem everyone is experiencing it though. It makes any fight looks really strange with a giant black box in the middle of the screen. Are there any ways to fix this personally or plans to bug fix it? This mod has been a huge lifesaver until now
