### ISSUE TITLE
Issue Launching the Game

### ISSUE THREAD

**Issue by KeiAres** [Lyall/GBFRelinkFix#5]
I'm getting a windows can't find WINEDLLOVERRIDES="dinput8=n,b" %command% when trying to launch the game via Steam.

**Comment by Lyall** [comment]
You don't need the launch command if you are running on Windows. Try deleting it and see if the game launches. I should really make the readme more clear since I've had a few people complain of this same issue.

**Comment by cloud0124** [comment]
sadly I'm also having trouble getting this to work on Win 11, even after trying w/o the launch commands. Launch commands will leave the app unable to start, and w/o I don't see this mods options in the menu's.
